[package]
name = "launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { package = "gtk4", version = "0.10" }
gtk4-layer-shell = "0.7.0"
fuzzy-matcher = "0.3.7"
evalexpr = "13.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
toml = "1.1.2"
dirs = "6.0.0"
