use std::fmt::Debug;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SearchResult {
    /// Unique ID for the result (e.g. "calc:2+2", "sys:reboot", "win:128")
    pub id: String,
    /// Main text displayed to the user
    pub title: String,
    /// Explanatory subtitle
    pub description: Option<String>,
    /// Icon name or path (optional)
    pub icon: Option<String>,
    /// Score generated by matching algorithm (higher is better)
    pub score: i32,
    /// Absolute timestamp of when this item was last activated
    pub last_used: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExecutionResult {
    /// Successfully ran command; close the launcher window
    CloseLauncher,
    /// Keep launcher open (e.g., calculation copied, clipboard item selected)
    KeepOpen,
    /// Error encountered; display message in the UI
    Error(String),
}

pub trait LauncherPlugin: Send + Sync {
    /// Unique identifier for the plugin (e.g., "calculator", "window_switcher")
    fn id(&self) -> &str;

    /// Checks if the plugin handles/accepts this query (e.g., checking prefixes like "!g")
    fn accepts(&self, query: &str) -> bool;

    /// Returns matching search results weighted by local search logic
    fn query(&self, query: &str) -> Vec<SearchResult>;

    /// Executes the action corresponding to a selected result ID
    fn execute(&self, result_id: &str, shift_pressed: bool) -> ExecutionResult;
}
